routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/40', 'HomeController@noProfile')->name('noProfile');

Route::prefix('admin')->group(function (){
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');

    // Password reset routes
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
    Route::resource('contributions','Admin\AdminContributionController',['as' => 'admin']);
    Route::get('contributions/cat/{status}','Admin\AdminContributionController@statusCategory')->name('admin.contributions.category.index');
    Route::resource('loans/urequests','Admin\AdminLoanRequestController',['as' => 'admin.loans']);
    Route::resource('loans/repayments','Admin\AdminLoanRepaymentController',['as' => 'admin.loans']);
    Route::resource('loans','Admin\AdminLoanController',['as' => 'admin']);
    Route::put('/loans/updateStatus/{reference}','Admin\AdminLoanController@updateStatus')->name('admin.loans.updateStatus');
    Route::resource('members','Admin\AdminMemberProfileController',['as' => 'admin']);
    Route::resource('users','Admin\AdminPlatformUserController',['as' => 'admin']);

    
    Route::get('/users/createProfile/{email}','Admin\AdminPlatformUserController@createProfile')->name('admin.users.createProfile')->where('email','[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
});
Route::prefix('ccm')->group(function (){
    Route::get('/login', 'Auth\CCMemberLoginController@showLoginForm')->name('ccmember.login');
    Route::post('/login', 'Auth\CCMemberLoginController@login')->name('ccmember.login.submit');

    // Password reset routes
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('ccmember.password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('ccmember.password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('ccmember.password.reset');
    
    Route::resource('loans/urequests/{id}/feedback','CCMember\CCMLoanRequestCCFeedbackController',['as' => 'ccmember.loans.urequests']);
    Route::resource('loans/urequests','CCMember\CCMLoanRequestController',['as' => 'ccmember.loans']);

    Route::get('/', 'CCMemberController@index')->name('ccmember.dashboard');
});
Route::resource('contributions','ContributionController');
Route::get('contributions/cat/{status}','ContributionController@statusCategory')->name('contributions.category.index');
Route::put('loans/urequests/{id}/sendToCommittee','LoanRequestController@sendToCommittee')->name('loans.urequests.sendToCommittee');
Route::resource('loans/urequests','LoanRequestController',['as' => 'loans']);
Route::resource('loans/{loan_ref}/guarantors','GuarantorController',['as' => 'loans']);
Route::resource('loans/{loan_ref}/repayments','LoanRepaymentController',['as' => 'loans']);
Route::get('loans/guarantees','GuarantorController@guarantees')->name('loans.guarantees.index');
Route::put('loans/guarantees/{id}/approve','GuarantorController@approve')->name('loans.guarantees.approve');
Route::resource('loans','LoanController');
Route::get('/profile', 'MemberProfileController@index')->name('profile.index');
Route::get('/profile/edit', 'MemberProfileController@edit')->name('profile.edit');
Route::put('/profile', 'MemberProfileController@update')->name('profile.update');

app/Loan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Loan extends Model
{
    public $incrementing = false;
    public function loan_request(){
        return $this->belongsTo('App\LoanRequest');
    }
    public function repayments(){
        return $this->hasMany('App\LoanRepayment');
    }
    public const statuses = ['Deleted','Pending','Active','With Issue', 'Completed'];
    
    public function getStatusTextAttribute(){
        return $this::statuses[$this->status];
    }
}

app/LoanType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LoanType extends Model
{
    //public $table = "loan_types";
    public function getGuarantorRequiredAttribute(){
        return $this->id==1;
    }
    public function loan_requests(){
        return $this->hasMany('App\LoanRequest');
    }
}

app/Http/Controllers/LoanController.php
<?php

namespace App\Http\Controllers;

use App\Loan;
use App\LoanRepayment;
use Illuminate\Http\Request;

class LoanController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $profile = auth()->user()->profile;
        if($profile){
            $id= $profile->id;
            $loans = $profile->loans()->paginate(10);
            foreach (Loan::statuses as $key=> $status){
                $num= $profile->loans()->where('loans.status',$key)->count();
                if($num){
                    $counts[$status] = $num;
                }else{
                    $counts[$status] =0;
                }
            }                  
            
            return view('loans.index',compact('loans','counts'));
        }
        else{
            return redirect('/40');
        }
        //$loans =Loan::orderBy('created_at','desc')->paginate(10);
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Loan  $loan
     * @return \Illuminate\Http\Response
     */
    public function show($ref)
    {
        //$loan = auth()->user()->profile->loanRequests()->find($ref)->loan;
        $loan = auth()->user()->profile->loans()->where("loan_request_id",$ref)->first();
        $repayments = null;
        $counts = null;
        if($loan!=null){
            $repayments = $loan->repayments()->orderBy('created_at','desc')->paginate(10);
            foreach (LoanRepayment::statuses as $key=> $status){
                $num= LoanRepayment::where('loan_id',$loan->id)->where('loan_repayments.status',$key)->count();
                if($num){
                    $counts[$status] = $num;
                }else{
                    $counts[$status] =0;
                }
            } 
        }
        return view('loans.single', compact('loan','repayments','counts'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Loan  $loan
     * @return \Illuminate\Http\Response
     */
    public function edit(Loan $loan)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Loan  $loan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Loan $loan)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Loan  $loan
     * @return \Illuminate\Http\Response
     */
    public function destroy(Loan $loan)
    {
        //
    }
}

resources/views/admin/loans/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1>Member Loans<a href="{{route('admin.loans.urequests.index')}}" class="tiny ui button blue right floated inverted"> <i class="icon arrow left"></i>Back To Requests</a></h1>
    <div class="ui divider"></div> 
    
    @if(count($loans)>0)
        <div class="ui stackable segment grid">
            <div class="four wide sa-white column">
                <div class="sa-grid sa-grid-tile">
                    <h1 class="sa-grid-tile-number no-margin"> {{$loans->total()}}</h1>
                    <h3 class="sa-grid-tile-title no-margin">Loans</h3>
                    <small class="sa-grid-tile-description no-margin"></small>
                </div>
            </div>
            @foreach($counts as $key=>$count)
                @if($count!=0)
                    <div class="four wide sa-{{strtolower($key)}} column">
                        <div class="sa-grid sa-grid-tile">
                            <h1 class="sa-grid-tile-number no-margin">{{$count}}</h1>
                            <h3 class="sa-grid-tile-title no-margin">{{$key}}</h3>
                            <small class="sa-grid-tile-description no-margin">
                                <a class="ui button inverted" href="{{route('admin.loans.index')}}">
                                    <i class="eye icon"></i> View All
                                </a>
                            </small>
                        </div>
                    </div>                
                @endif
            @endforeach
        </div>
        <div class="ui hidden divider"></div>
        <div class="ui hidden divider"></div>
        <div class="ui container">
            <table class="ui table">
                <thead>
                    <th>Member</th>
                    <th>Reference Number</th>
                    <th>Amount</th>
                    <th>Date</th>
                    <th>Status</th>
                    <th></th>
                </thead>
                @foreach($loans as $loan)
                    <tr>
                        <td><a href="{{route('admin.members.show',$loan->loan_request->member_profile_id)}}">{{$loan->loan_request->member_profile->fullname}}</a></td>
                        <td><a href="{{route('admin.loans.show',$loan->loan_request_id)}}">{{$loan->loan_request_id}}</a></td>
                        <td>{{$loan->amount}}</td>
                        <td>{{$loan->created_at}}</td>
                        <td>{{$loan->statusText}}</td>
                        <td>
                            @if($loan->status==1)
                                <form class="ui form" method="post" action="{{route('admin.loans.updateStatus',$loan->loan_request_id)}}">
                                    {{ csrf_field() }}
                                    <input type="hidden" value="{{$loan->loan_request_id}}" name="referenced">
                                    <input type="hidden" value="2" name="status">
                                    <input type="submit" value="Activate" class="ui button blue"/>
                                    {{ method_field('PUT') }}
                                </form>
                            @else
                                <a class="ui tiny button blue" href="{{route('admin.loans.show',$loan->loan_request_id)}}">View Details</a>
                            @endif
                        </td>
                    </tr>
                @endforeach
            </table>
            {{$loans->links()}}
        </div>
    @else
        <p>There were no Contributions. So, here is a general Message</p>
    @endif
</div>
@endsection

resources/views/admin/loans/single.blade.php
@extends('layouts.app')

@section('content')
<div class="ui">    
    @if($loan)
        <div class="ui segment">
            <h1>Loan <a href="{{route('admin.loans.index')}}" class="tiny ui button blue right floated inverted"> <i class="icon arrow left"></i>Back To Loans</a></h1>
        </div>
        <div class="ui segment">
            <p>Refernce Num: {{$loan->loan_request_id}}</p>            
            <p>Requested By: {{$loan->loan_request->member_profile->fullname}}</p>
            <p>Amount: {{$loan->amount}} </p>
            <p>Date: {{$loan->created_at}}</p>
            <p>Status: {{$loan->statusText}}</p>
            <p>
                @if($loan->status==1)
                    <form class="ui form" method="post" action="{{route('admin.loans.updateStatus',$loan->loan_request_id)}}">
                        {{ csrf_field() }}
                        <input type="hidden" value="{{$loan->loan_request_id}}" name="referenced">
                        <input type="hidden" value="2" name="status">
                        <input type="submit" value="Activate" class="ui button blue"/>
                        {{ method_field('PUT') }}
                    </form>
                @endif
            </p>
        </div>
        <div class="ui divider"></div> 
        @if($repayments && count($repayments)>0)     
            <div class="ui stackable segment grid">
                <div class="four wide sa-white column">
                    <div class="sa-grid sa-grid-tile">
                        <h1 class="sa-grid-tile-number no-margin"> {{$repayments->total()}}</h1>
                        <h3 class="sa-grid-tile-title no-margin">Loan Repayments</h3>
                        <small class="sa-grid-tile-description no-margin"><a href="{{route('admin.loans.repayments.create')}}" class="ui tiny button blue">Add Repayment</a></small>
                    </div>
                </div>
                @if($counts)
                    @foreach($counts as $key=>$count)
                        @if($count!=0)
                            <div class="four wide sa-{{strtolower($key)}} column">
                                <div class="sa-grid sa-grid-tile">
                                    <h1 class="sa-grid-tile-number no-margin">{{$count}}</h1>
                                    <h3 class="sa-grid-tile-title no-margin">{{$key}}</h3>
                                    <small class="sa-grid-tile-description no-margin">
                                        <a class="ui button inverted" href="{{route('loans.index')}}">
                                            <i class="eye icon"></i> View All
                                        </a>
                                    </small>
                                </div>
                            </div>                
                        @endif
                    @endforeach
                @endif
            </div>
            
            <table class="ui table">
                <thead>
                    <th>Reference Number</th>
                    <th>Amount</th>
                    <th>Date</th>
                    <th>Status</th>
                    <th></th>
                </thead>
                @foreach($repayments as $repayment)
                    <tr>
                        <td><a href="{{route('admin.loans.repayments.show',$repayment->reference)}}">{{$repayment->reference}}</td>
                        <td>{{$repayment->amount}}</td>
                        <td>{{$repayment->created_at}}</td>
                        <td>{{$repayment->statusText}}</td>
                    </tr>
                @endforeach
            </table>
        @endif
    @else
        <p>There seems to be something wrong</p>
    @endif
</div>
@endsection