routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/40', 'HomeController@noProfile')->name('noProfile');

Route::prefix('admin')->group(function (){
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');

    // Password reset routes
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
    Route::resource('contributions','Admin\AdminContributionController',['as' => 'admin']);
    Route::get('contributions/cat/{status}','Admin\AdminContributionController@statusCategory')->name('admin.contributions.category.index');
    Route::resource('loans/urequests','Admin\AdminLoanRequestController',['as' => 'admin.loans']);
    Route::resource('loans/repayments','Admin\AdminLoanRepaymentController',['as' => 'admin.loans']);
    Route::resource('loans','Admin\AdminLoanController',['as' => 'admin']);
    Route::put('/loans/updateStatus/{reference}','Admin\AdminLoanController@updateStatus')->name('admin.loans.updateStatus');
    Route::resource('members','Admin\AdminMemberProfileController',['as' => 'admin']);
    Route::resource('users','Admin\AdminPlatformUserController',['as' => 'admin']);

    
    Route::get('/users/createProfile/{email}','Admin\AdminPlatformUserController@createProfile')->name('admin.users.createProfile')->where('email','[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
});
Route::prefix('ccm')->group(function (){
    Route::get('/login', 'Auth\CCMemberLoginController@showLoginForm')->name('ccmember.login');
    Route::post('/login', 'Auth\CCMemberLoginController@login')->name('ccmember.login.submit');

    // Password reset routes
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('ccmember.password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('ccmember.password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('ccmember.password.reset');
    
    Route::resource('loans/urequests/{id}/feedback','CCMember\CCMLoanRequestCCFeedbackController',['as' => 'ccmember.loans.urequests']);
    Route::resource('loans/urequests','CCMember\CCMLoanRequestController',['as' => 'ccmember.loans']);

    Route::get('/', 'CCMemberController@index')->name('ccmember.dashboard');
});
Route::resource('contributions','ContributionController');
Route::get('contributions/cat/{status}','ContributionController@statusCategory')->name('contributions.category.index');
Route::put('loans/urequests/{id}/sendToCommittee','LoanRequestController@sendToCommittee')->name('loans.urequests.sendToCommittee');
Route::resource('loans/urequests','LoanRequestController',['as' => 'loans']);
Route::resource('loans/{loan_ref}/guarantors','GuarantorController',['as' => 'loans']);
Route::resource('loans/{loan_ref}/repayments','LoanRepaymentController',['as' => 'loans']);
Route::get('loans/guarantees','GuarantorController@guarantees')->name('loans.guarantees.index');
Route::put('loans/guarantees/{id}/approve','GuarantorController@approve')->name('loans.guarantees.approve');
Route::resource('loans','LoanController');
Route::get('/profile', 'MemberProfileController@index')->name('profile.index');
Route::get('/profile/edit', 'MemberProfileController@edit')->name('profile.edit');
Route::put('/profile', 'MemberProfileController@update')->name('profile.update');

resources/views/admin/members/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h3>Add Profile Details for {{$user->email}}</h3>
        <form class="ui form" method="post" action="{{route('admin.members.store')}}">
            {{ csrf_field() }}
            <div class="field">
                <label>Name</label>
                <input type="text" id="" name="name" class="form-control" placeholder="Full Name" required="" autofocus="">
            </div>
            <div class="field">
                <label>Id Number</label>
                <input type="text" id="" name="national" class="form-control" placeholder="Id Num" required="">
            </div>
            <div class="field">
                <label>Phone</label>
                <input type="text" id="" name="phone" class="form-control" placeholder="Phone" required="">
            </div>
            <div class="field">
                <label>Postal</label>
                <input type="text" id="" name="postal" class="form-control" placeholder="Postal" required="">
            </div>
            
            <input type="hidden" value="{{$user->email}}" name="email">
            <input type="submit" value="Submit" class="ui button blue"/>
        </form>
    </div>
@endsection

resources/views/admin/members/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="ui segment">
        <h3>Edit Profile Details for Account <a href="{{route('admin.members.index')}}" class="ui tiny button blue right floated inverted"><i class="icon arrow left"></i> Back To Members</a></h3>
        <div class="ui divider"></div> 
        <form class="ui form" method="post" action="{{route('admin.members.update',$member->id)}}">
            {{ csrf_field() }}
            <div class="field">
                <label>Name</label>
                <input type="text" id="" name="name" class="form-control" placeholder="Full Name" value="{{$member->fullname}}" required="" autofocus="">
            </div>
            <div class="field">
                <label>Id Number</label>
                <input type="text" id="" name="national" class="form-control" placeholder="Id Num" value="{{$member->national_id}}" required="">
            </div>
            <div class="field">
                <label>Phone</label>
                <input type="text" id="" name="phone" class="form-control" placeholder="Phone" value="{{$member->phone}}" required="">
            </div>
            <div class="field">
                <label>Postal</label>
                <input type="text" id="" name="postal" class="form-control" placeholder="Postal" value="{{$member->postal}}" required="">
            </div>
            <div class="field">
                <label>Account Status</label>
                <select id="sacco-member-status" name="status" class="ui search dropdown">
                    @if($statuses)
                        @foreach($statuses as $key=>$status)
                            <option value="{{$key}}">{{$status}}</option>
                        @endforeach
                    @endif
                </select>
            </div>
            
            <input type="hidden" value="{{$member->user->email}}" name="email">
            <input type="hidden" value="{{$member->id}}" name="member_num">
            {{ method_field('PUT') }}
       
            <div class="field">
                <label></label>
                <input type="submit" value="Submit" class="ui button blue"/>
            </div>
        </form>
        
        <script>     
            $(document).ready(function() {   
                $('select#sacco-member-status').dropdown('set selected', {{$member->status}});
            });
        </script>
    </div>
@endsection

resources/views/admin/members/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1>Sacco Members<a href="{{route('admin.users.index')}}" class="ui tiny button blue right floated"><i class="icon eye"></i> View Registered Users</a></h1>
    
    <div class="ui hidden divider"></div> 
    @if(count($members)>0)
        <div class="ui stackable segment grid">
            <div class="four wide sa-white column">
                <div class="sa-grid sa-grid-tile">
                    <h1 class="sa-grid-tile-number no-margin"> {{$members->total()}}</h1>
                    <h3 class="sa-grid-tile-title no-margin">Members</h3>
                    <small class="sa-grid-tile-description no-margin"></small>
                </div>
            </div>
            @foreach($counts as $key=>$count)
                @if($count!=0)
                    <div class="four wide sa-{{strtolower($key)}} column">
                        <div class="sa-grid sa-grid-tile">
                            <h1 class="sa-grid-tile-number no-margin">{{$count}}</h1>
                            <h3 class="sa-grid-tile-title no-margin">{{$key}}</h3>
                            <small class="sa-grid-tile-description no-margin">
                                <a class="ui button inverted" href="{{route('admin.members.index')}}">
                                    <i class="eye icon"></i> View All
                                </a>
                            </small>
                        </div>
                    </div>                
                @endif
            @endforeach
        </div>
        <div class="ui hidden divider"></div>
        <div class="ui hidden divider"></div>
        <div class="ui container"> 
            <table class="ui table">
                <thead>
                    <th>Member Num</th>
                    <th>Name</th>
                    <th>National ID</th>
                    <th>Phone</th>
                    <th>Postal Address</th>
                    <th>Registered</th>
                    <th>Status</th>
                    <th></th>
                </thead>
                @foreach($members as $member)
                    <tr>
                        <td><a href="{{route('admin.members.show',$member->id)}}">{{$member->id}}</a></td>
                        <td>{{$member->fullname}}</td>
                        <td>{{$member->national_id}}</td>
                        <td>{{$member->phone}}</td>
                        <td>{{$member->postal}}</td>
                        <td>{{$member->created_at}}</td>
                        <td>{{$member->statusText}}</td>
                        <td><a class="ui tiny button blue" href="{{route('admin.members.edit',$member->id)}}">Edit</a></td>
                    </tr>
                @endforeach
            </table>
            {{$members->links()}}
        </div>
    @else
        <p>There were no Members found on the system.</p>
    @endif
</div>
@endsection

resources/views/admin/members/single.blade.php
@extends('layouts.app')

@section('content')
<div class="ui segment">
    @if($member)
        <h1>Profile {{$member->id}}<a href="{{route('admin.members.edit',$member->id)}}" class="ui tiny button blue right floated">Edit Member Profile</a></h1>
        <div class="ui divider"></div> 
        <p>Hey {{$member->fullname}} </p>
        <p>ID Number: {{$member->national_id}} </p>
        <p>Phone Number: {{$member->phone}} </p>
        <p>Postal: {{$member->postal}} </p>
        <p>Status: {{$member->statusText}} </p>
    @else
        <p>There was an error. Kindly ensure you are a member</p>
    @endif
</div>
@endsection