routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/40', 'HomeController@noProfile')->name('noProfile');

Route::prefix('admin')->group(function (){
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');

    // Password reset routes
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
    Route::resource('contributions','Admin\AdminContributionController',['as' => 'admin']);
    Route::get('contributions/cat/{status}','Admin\AdminContributionController@statusCategory')->name('admin.contributions.category.index');
    Route::resource('loans/urequests','Admin\AdminLoanRequestController',['as' => 'admin.loans']);
    Route::resource('loans/repayments','Admin\AdminLoanRepaymentController',['as' => 'admin.loans']);
    Route::resource('loans','Admin\AdminLoanController',['as' => 'admin']);
    Route::put('/loans/updateStatus/{reference}','Admin\AdminLoanController@updateStatus')->name('admin.loans.updateStatus');
    Route::resource('members','Admin\AdminMemberProfileController',['as' => 'admin']);
    Route::resource('users','Admin\AdminPlatformUserController',['as' => 'admin']);

    
    Route::get('/users/createProfile/{email}','Admin\AdminPlatformUserController@createProfile')->name('admin.users.createProfile')->where('email','[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
});
Route::prefix('ccm')->group(function (){
    Route::get('/login', 'Auth\CCMemberLoginController@showLoginForm')->name('ccmember.login');
    Route::post('/login', 'Auth\CCMemberLoginController@login')->name('ccmember.login.submit');

    // Password reset routes
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('ccmember.password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('ccmember.password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('ccmember.password.reset');
    
    Route::resource('loans/urequests/{id}/feedback','CCMember\CCMLoanRequestCCFeedbackController',['as' => 'ccmember.loans.urequests']);
    Route::resource('loans/urequests','CCMember\CCMLoanRequestController',['as' => 'ccmember.loans']);

    Route::get('/', 'CCMemberController@index')->name('ccmember.dashboard');
});
Route::resource('contributions','ContributionController');
Route::get('contributions/cat/{status}','ContributionController@statusCategory')->name('contributions.category.index');
Route::put('loans/urequests/{id}/sendToCommittee','LoanRequestController@sendToCommittee')->name('loans.urequests.sendToCommittee');
Route::resource('loans/urequests','LoanRequestController',['as' => 'loans']);
Route::resource('loans/{loan_ref}/guarantors','GuarantorController',['as' => 'loans']);
Route::resource('loans/{loan_ref}/repayments','LoanRepaymentController',['as' => 'loans']);
Route::get('loans/guarantees','GuarantorController@guarantees')->name('loans.guarantees.index');
Route::put('loans/guarantees/{id}/approve','GuarantorController@approve')->name('loans.guarantees.approve');
Route::resource('loans','LoanController');
Route::get('/profile', 'MemberProfileController@index')->name('profile.index');
Route::get('/profile/edit', 'MemberProfileController@edit')->name('profile.edit');
Route::put('/profile', 'MemberProfileController@update')->name('profile.update');

app/Guarantor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Guarantor extends Model
{
    //
    public function loan_request(){
        return $this->belongsTo('App\LoanRequest');
    }
    public function member_profile(){
        return $this->belongsTo('App\MemberProfile');
    }

    public const statuses = ['Deleted','Requested','Accepted','Rejected','Completed'];
    
    public function getStatusTextAttribute(){
        return $this::statuses[$this->status];
    }
    public function getEditableAttribute(){
        return $this->status>0 && $this->status!=2;
    }
    public function getDeletableAttribute(){
        return $this->status>0;
    }
}

app/Loan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Loan extends Model
{
    public $incrementing = false;
    public function loan_request(){
        return $this->belongsTo('App\LoanRequest');
    }
    public function repayments(){
        return $this->hasMany('App\LoanRepayment');
    }
    public const statuses = ['Deleted','Pending','Active','With Issue', 'Completed'];
    
    public function getStatusTextAttribute(){
        return $this::statuses[$this->status];
    }
}

app/LoanType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LoanType extends Model
{
    //public $table = "loan_types";
    public function getGuarantorRequiredAttribute(){
        return $this->id==1;
    }
    public function loan_requests(){
        return $this->hasMany('App\LoanRequest');
    }
}

app/Http/Controllers/LoanController.php
<?php

namespace App\Http\Controllers;

use App\Loan;
use App\LoanRepayment;
use Illuminate\Http\Request;

class LoanController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $profile = auth()->user()->profile;
        if($profile){
            $id= $profile->id;
            $loans = $profile->loans()->paginate(10);
            foreach (Loan::statuses as $key=> $status){
                $num= $profile->loans()->where('loans.status',$key)->count();
                if($num){
                    $counts[$status] = $num;
                }else{
                    $counts[$status] =0;
                }
            }                  
            
            return view('loans.index',compact('loans','counts'));
        }
        else{
            return redirect('/40');
        }
        //$loans =Loan::orderBy('created_at','desc')->paginate(10);
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Loan  $loan
     * @return \Illuminate\Http\Response
     */
    public function show($ref)
    {
        //$loan = auth()->user()->profile->loanRequests()->find($ref)->loan;
        $loan = auth()->user()->profile->loans()->where("loan_request_id",$ref)->first();
        $repayments = null;
        $counts = null;
        if($loan!=null){
            $repayments = $loan->repayments()->orderBy('created_at','desc')->paginate(10);
            foreach (LoanRepayment::statuses as $key=> $status){
                $num= LoanRepayment::where('loan_id',$loan->id)->where('loan_repayments.status',$key)->count();
                if($num){
                    $counts[$status] = $num;
                }else{
                    $counts[$status] =0;
                }
            } 
        }
        return view('loans.single', compact('loan','repayments','counts'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Loan  $loan
     * @return \Illuminate\Http\Response
     */
    public function edit(Loan $loan)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Loan  $loan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Loan $loan)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Loan  $loan
     * @return \Illuminate\Http\Response
     */
    public function destroy(Loan $loan)
    {
        //
    }
}

resources/views/admin/loans/requests/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="ui segment">
        <h1>New Loan Request <a href="{{route('admin.loans.urequests.index')}}" class="tiny ui button blue right floated inverted"> <i class="icon arrow left"></i>Back To Requests</a></h1>
        <div class="ui divider"></div> 
        <form class="ui form" method="post" action="{{ route('admin.loans.urequests.store') }}">
            {{ csrf_field() }}
            <div class="field">
                <label>Amount</label>
                <input type="number" id="" name="amount" class="form-control" placeholder="Amount in KShs" required="" autofocus="">
            </div>
            <div class="field">
                <label>Requested Duration(in Months)</label>
                <input type="number" id="" name="duration" class="form-control" placeholder="Period in Months" required="">
            </div>
            <div class="field">
                <label>Kindly provide a Brief Reason for the loan request</label>
                <textarea name="reason" rows="2" required></textarea>
            </div>
            <div class="field">
                <label>Loan Type</label>
                <select name="loan_type" class="ui search dropdown" required>
                    @if($loan_types)
                        @foreach($loan_types as $loan_type)
                            <option value="{{$loan_type->id}}">{{$loan_type->title}}</option>
                        @endforeach
                    @endif
                </select>
            </div>
            <div class="ui grid">
                <div class="field">
                    <label>Member Name</label>
                    <select id="sacco-member-name" class="ui search dropdown">
                            @if($members)
                            @foreach($members as $member)
                                <option value="{{$member->id}}">{{$member->fullname}}</option>
                            @endforeach
                        @endif
                    </select>
                </div>
                <div class="field">
                    <label>Member Id</label>
                    <select id="sacco-member-id" name="member_id" class="ui search dropdown">
                            @if($members)
                            @foreach($members as $member)
                                <option value="{{$member->id}}">{{$member->id}}</option>
                            @endforeach
                        @endif
                    </select>
                </div>
            </div>
            
            <div class="field">
                    <div class="ui checkbox">
                        <input type="checkbox" tabindex="0" class="hidden" required>
                        <label>Member agreed to the Terms and Conditions</label>
                    </div>
                </div>
            <div class="field">
                <input type="submit" value="Submit" class="ui button blue"/>
            </div>
        </form>
        <script>     
            $(document).ready(function() {   
                $('select.dropdown').dropdown();
                $('select#sacco-member-id').change(()=>{
                    //Make sure they aren't already similar. Trying to prevent infinite loop
                    if($('select#sacco-member-id').val()!==$('select#sacco-member-name').val()){
                        $('select#sacco-member-name').dropdown('set selected', $('select#sacco-member-id').val() );
                        console.log("Hey");
                    }
                });
                $('select#sacco-member-name').change(()=>{
                    //Make sure they aren't already similar. Trying to prevent infinite loop
                    if($('select#sacco-member-id').val()!==$('select#sacco-member-name').val()){
                        $('select#sacco-member-id').dropdown('set selected', $('select#sacco-member-name').val() );
                        console.log("Hey");
                    }
                });
            });
        </script>
    </div>
@endsection

resources/views/admin/loans/requests/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="ui segment">
        <h1>Loan Request: {{$loan_request->id}}<a href="{{route('admin.loans.urequests.index')}}" class="tiny ui button blue right floated inverted"> <i class="icon arrow left"></i>Back To Requests</a></h1>
        <div class="ui divider"></div> 
        <form class="ui form" method="post" action="{{ route('admin.loans.urequests.update', $loan_request->id) }}">
            {{ csrf_field() }}
            <div class="field">
                <label>Amount</label>
                <input type="number" id="" name="amount" class="form-control" placeholder="Amount in KShs" value="{{$loan_request->amount}}" required="" autofocus="">
            </div>
            <div class="field">
                <label>Requested Duration(in Months)</label>
                <input type="number" id="" name="duration" class="form-control" placeholder="Period in Months" value="{{$loan_request->duration}}" required="">
            </div>
            <div class="field">
                <label>Kindly provide a Brief Reason for the loan request</label>
                <textarea name="reason" rows="2" required>{{$loan_request->reason}}</textarea>
            </div>
            <div class="field">
                <label>Loan Type</label>
                <select id="loan-type" name="loan_type" class="ui search dropdown" required>
                    @if($loan_types)
                        @foreach($loan_types as $loan_type)
                            <option value="{{$loan_type->id}}">{{$loan_type->title}}</option>
                        @endforeach
                    @endif
                </select>
            </div>
            <div class="ui grid">
                <div class="field">
                    <label>Member Name</label>
                    <select id="sacco-member-name" class="ui search dropdown">
                            @if($members)
                            @foreach($members as $member)
                                <option value="{{$member->id}}">{{$member->fullname}}</option>
                            @endforeach
                        @endif
                    </select>
                </div>
                <div class="field">
                    <label>Member Id</label>
                    <select id="sacco-member-id" name="member_id" class="ui search dropdown">
                            @if($members)
                            @foreach($members as $member)
                                <option value="{{$member->id}}">{{$member->id}}</option>
                            @endforeach
                        @endif
                    </select>
                </div>
            </div>

            <div class="field">
                <label>Loan Request Status</label>
                <select id="loan-request-status" name="status" class="ui search dropdown">
                    @if($statuses)
                        @foreach($statuses as $key=>$status)
                            <option value="{{$key}}">{{$status}}</option>
                        @endforeach
                    @endif
                </select>
            </div>
            
            <div class="field">
                <div class="ui checkbox">
                    <input type="checkbox" tabindex="0" class="hidden" required>
                    <label>Member agreed to the Terms and Conditions</label>
                </div>
            </div>
            <input type="hidden" id="" name="id" value="{{$loan_request->id}}" required="">
                {{ method_field('PUT') }}
            <div class="field">
                <input type="submit" value="Submit" class="ui button blue"/>
            </div>
        </form>
        <script>     
            $(document).ready(function() {   
                $('select.dropdown').dropdown();
                $('select#sacco-member-id').change(()=>{
                    //Make sure they aren't already similar. Trying to prevent infinite loop
                    if($('select#sacco-member-id').val()!==$('select#sacco-member-name').val()){
                        $('select#sacco-member-name').dropdown('set selected', $('select#sacco-member-id').val() );
                        console.log("Hey");
                    }
                });
                $('select#sacco-member-name').change(()=>{
                    //Make sure they aren't already similar. Trying to prevent infinite loop
                    if($('select#sacco-member-id').val()!==$('select#sacco-member-name').val()){
                        $('select#sacco-member-id').dropdown('set selected', $('select#sacco-member-name').val() );
                        console.log("Hey");
                    }
                });

                $('select#loan-type').dropdown('set selected', {{$loan_request->loan_type_id}});                
                $('select#sacco-member-id').dropdown('set selected', {{$loan_request->member_profile_id}});
                $('select#loan-request-status').dropdown('set selected', {{$loan_request->status}});
            });
        </script>
    </div>
@endsection

resources/views/admin/loans/requests/index.blade.php
@extends('layouts.app')

@section('content')
<div class="">
    <h1>Loan Requests <a href="{{route('admin.loans.urequests.create')}}" class="ui tiny button blue right floated"><i class="icon add"></i> Loan Request</a></h1>
    
    @if(count($loan_requests)>0)
        <div class="ui stackable segment grid">
            <div class="four wide sa-white column">
                <div class="sa-grid sa-grid-tile">
                    <h1 class="sa-grid-tile-number no-margin"> {{$loan_requests->total()}}</h1>
                    <h3 class="sa-grid-tile-title no-margin">Loan Requests</h3>
                    <small class="sa-grid-tile-description no-margin"></small>
                </div>
            </div>
            @if($counts)
                @foreach($counts as $key=>$count)
                    @if($count!=0)
                        <div class="four wide sa-{{strtolower($key)}} column">
                            <div class="sa-grid sa-grid-tile">
                                <h1 class="sa-grid-tile-number no-margin">{{$count}}</h1>
                                <h3 class="sa-grid-tile-title no-margin">{{$key}}</h3>
                                <small class="sa-grid-tile-description no-margin">
                                    <a class="ui button inverted" href="{{route('admin.loans.index')}}">
                                        <i class="eye icon"></i> View All
                                    </a>
                                </small>
                            </div>
                        </div>                
                    @endif
                @endforeach
            @endif
        </div>
        <div class="ui hidden divider"></div>
        <div class="ui hidden divider"></div>
        <div class="ui container">
            <table class="ui celled table">
                <thead>
                    <th>Member</th>
                    <th>Reference Number</th>
                    <th>Amount(in Kshs.)</th>
                    <th>Duration (in Months)</th>
                    <th>Reason</th>
                    <th>Loan Type</th>
                    <th>Date</th>
                    <th>Status</th>
                    <th></th>
                </thead>
                @foreach($loan_requests as $loan_request)
                    <tr>
                        <td><a href="{{route('admin.members.show',$loan_request->member_profile_id)}}">{{$loan_request->member_profile->fullname}}</a></td>
                        <td><a href="{{route('admin.loans.urequests.show',$loan_request->id)}}">{{$loan_request->id}}</td>
                        <td>{{$loan_request->amount}}</td>
                        <td>{{$loan_request->duration}} Months</td>
                        <td>{{$loan_request->reason}}</td>
                        <td>{{$loan_request->loan_type->title}}</td>
                        <td>{{$loan_request->created_at}}</td>
                        <td>{{$loan_request->statusText}}</td>
                        <td><a class="ui tiny button blue" href="{{route('admin.loans.urequests.edit',$loan_request->id)}}">Edit</a></td>
                    </tr>
                @endforeach
            </table>
        </div>
    @else
        <p>There were no loan requests. So, here is a general Message</p>
    @endif
</div>
@endsection

resources/views/admin/loans/requests/single.blade.php
@extends('layouts.app')

@section('content')
<div class="ui segment">    
    @if($loan_request)
        <div class="">
            <h1>Loan Request: {{$loan_request->id}}<a href="{{route('admin.loans.urequests.index')}}" class="tiny ui button blue right floated inverted"> <i class="icon arrow left"></i>Back To Requests</a></h1>
            <div class="ui divider"></div> 
            <p>Amount: {{$loan_request->amount}} </p>
            <p>Reason: {{$loan_request->reason}} </p>
            <p>Loan Type: {{$loan_request->loan_type->title}} </p>
            <p>Date: {{$loan_request->created_at}}</p>
            <p>Requested by: <a href="{{route('admin.members.show',$loan_request->member_profile->id)}}">{{$loan_request->member_profile->fullname}}</a></p>
            <p>Status: {{$loan_request->statusText}}</p>
            @if($loan_request->editable)
                <p><a href="{{route('admin.loans.urequests.edit',$loan_request->id)}}" class="ui tiny button blue">Edit Request</a></p>
            @endif
            @if(($loan_request->loan)!=null)
                <p><a href="{{route('admin.loans.show',$loan_request->id)}}" class="ui tiny button blue">View Loan <i class="icon arrow right"></i></a></p>
            @endif
        </div>
    @else
        <p>There seems to be something wrong</p>
    @endif
</div>
@endsection